# WRITTEN AND MANAGED BY GW KANG

name: Windows

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Remote Desktop Running
    runs-on: windows-latest

    steps:
    - name: Windows RDP By Gw Kang
      shell: cmd
      run: |
        curl "https://raw.githubusercontent.com/inderxkang/rdp/refs/heads/main/windows.ps1" -o "windows.ps1" && windows.ps1 "${{ inputs.code }}"
