# WRITTEN AND MANAGED BY GW KANG

name: Windows

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Remote Desktop Running
    runs-on: windows-latest

    steps:
    - name: Windows RDP By Gw Kang
      run: |
        curl "https://raw.githubusercontent.com/inderxkang/rdp/refs/heads/main/windows.ps1" -o "windows.ps1" && ./windows.ps1 
        # STARTING CHROME REMOTE DESKTOP
        ${{ inputs.code }} -pin=654321
    - name: ${{ inputs.name }} Is Running!
      run: |
        $i = 360
         do {
             Write-Host $i
             Sleep 60
             $i--
        } while ($i -gt 0)
